version: '3'

services:

  mysqldb:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mystorage:/var/lib/mysql
    restart: always

  zookeeper:
    image: library/zookeeper:3.4.13
    environment:
      ZOO_MY_ID: 1
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    ports:
       - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      BROKER_ID_COMMAND: "hostname | cut -d'-' -f2"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "logging:20:1"
      KAFKA_LISTENERS: "PLAINTEXT://:9092"
    restart: always


  event:
    build:
      context: "" #Sport
      dockerfile: event/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_DATABASE=${DB_DATABASE}
    restart: always

  consumer_logging:
    build:
     context: "" #Sport
     dockerfile: consumer_logging/Dockerfile
    ports:
       - "8082:8082"
    environment:
         - MYSQL_HOST=${DB_HOST}
         - MYSQL_DATABASE=${DB_DATABASE}
    restart: always

  api_gateway:
     build:
      context: . #Sport
      dockerfile: API_gateway/Dockerfile
     ports:
      - "9000:9000"
     restart: always



volumes:
  mystorage: